/*
 * Harness feature flag analytics service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.harness.cfsdk.cloud.analytics.model;

import androidx.annotation.Nullable;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Metrics
 */
public class Metrics {

    public static final String SERIALIZED_NAME_METRICS_DATA = "metricsData";
    @SerializedName(SERIALIZED_NAME_METRICS_DATA)
    private List<MetricsData> metricsData = null;

    public Metrics metricsData(List<MetricsData> metricsData) {

        this.metricsData = metricsData;
        return this;
    }

    public Metrics addMetricsDataItem(MetricsData metricsDataItem) {
        if (this.metricsData == null) {
            this.metricsData = new ArrayList<>();
        }
        this.metricsData.add(metricsDataItem);
        return this;
    }

    /**
     * Get metricsData
     *
     * @return metricsData
     **/
    @Nullable
    @ApiModelProperty(value = "")
    public List<MetricsData> getMetricsData() {
        return metricsData;
    }

    public void setMetricsData(List<MetricsData> metricsData) {
        this.metricsData = metricsData;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Metrics metrics = (Metrics) o;
        return // Objects.equals(this.targetData, metrics.targetData) &&
                Objects.equals(this.metricsData, metrics.metricsData);
    }

    @Override
    public int hashCode() {

        // return Objects.hash(targetData, metricsData);
        return Objects.hash(metricsData);
    }


    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("class Metrics {\n");
        sb.append("    metricsData: ").append(toIndentedString(metricsData)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
