buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'org.owasp:dependency-check-gradle:9.0.9'
  }
}

plugins {
    id 'com.android.library'
    id "com.vanniktech.maven.publish" version "0.33.0"
}

subprojects {
    apply plugin: 'org.owasp.dependencycheck'
}

def getVersionCode(semVer) {
    def version = semVer.replace("-SNAPSHOT", "").replaceAll("[.]", "").toInteger()
    println version
    return version
}

android {
    namespace = "io.harness.cfsdk"

    compileSdkVersion 33
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33
        consumerProguardFiles "consumer-rules.pro"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        // Desugaring options allow us to get access to Java 8 APIs that aren't available on our
        // minSdkVersion 21, in particular atomic compute functions in ConcurrentHashMap<>
        // see https://developer.android.com/studio/write/java8-support#library-desugaring
        coreLibraryDesugaringEnabled = true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig = false
    }
}

import com.vanniktech.maven.publish.SonatypeHost
import com.vanniktech.maven.publish.AndroidSingleVariantLibrary

mavenPublishing {
    coordinates("io.harness", "ff-android-client-sdk", libs.versions.sdk.get())

    publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)
    signAllPublications()
    configure(new AndroidSingleVariantLibrary("release", true, true))

    pom {
        name = "ff-android-client-sdk"
        description = 'This is the official Android SDK for Harness Feature Flags Service'
        url = 'https://github.com/harness/ff-android-client-sdk'
        licenses {
            license {
                name = 'Apache-2.0 License'
                url = 'https://github.com/harness/ff-android-client-sdk/blob/main/LICENSE'
            }
        }
        developers {
            developer {
                id = 'andybharness'
                name = 'Andrew Bell'
                email = 'andrew.bell@harness.io'
            }
        }
        scm {
            connection = 'scm:git:https://github.com/harness/ff-android-client-sdk.git'
            developerConnection = 'scm:git:ssh://github.com/harness/ff-android-client-sdk.git'
            url = 'https://github.com/harness/ff-android-client-sdk/tree/main'
        }
    }
}

dependencies {

    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.3")

    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'androidx.annotation:annotation:1.7.0'
    implementation "com.squareup.okhttp3:okhttp:$okhttp3_version"
    implementation "com.squareup.okhttp3:logging-interceptor:$okhttp3_version"
    implementation 'io.swagger:swagger-annotations:1.5.24'
    implementation 'com.google.code.gson:gson:2.10.1'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:4.10.0'
    testImplementation "com.squareup.okhttp3:mockwebserver:$okhttp3_version"
    testImplementation "com.squareup.okhttp3:okhttp-tls:$okhttp3_version"
    testImplementation 'org.json:json:20230227'
    testImplementation 'com.google.guava:guava:31.1-android'
    testImplementation 'ch.qos.logback:logback-classic:1.2.11'
    testImplementation 'com.github.tony19:logback-android:3.0.0'
}

tasks.withType(Javadoc) {
    failOnError false // openapi generated code has errors
    options.addStringOption('Xdoclint:none', '-quiet')
    options.addStringOption('encoding', 'UTF-8')
    options.addStringOption('charSet', 'UTF-8')
}