/*
 * Harness feature flag service client apis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.harness.cfsdk.cloud.core.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Distribution
 */
public class Distribution {
  public static final String SERIALIZED_NAME_BUCKET_BY = "bucketBy";
  @SerializedName(SERIALIZED_NAME_BUCKET_BY)
  private String bucketBy;

  public static final String SERIALIZED_NAME_VARIATIONS = "variations";
  @SerializedName(SERIALIZED_NAME_VARIATIONS)
  private List<WeightedVariation> variations = new ArrayList<>();


  public Distribution bucketBy(String bucketBy) {
    
    this.bucketBy = bucketBy;
    return this;
  }

   /**
   * Get bucketBy
   * @return bucketBy
  **/
  @ApiModelProperty(required = true, value = "")

  public String getBucketBy() {
    return bucketBy;
  }


  public void setBucketBy(String bucketBy) {
    this.bucketBy = bucketBy;
  }


  public Distribution variations(List<WeightedVariation> variations) {
    
    this.variations = variations;
    return this;
  }

  public Distribution addVariationsItem(WeightedVariation variationsItem) {
    this.variations.add(variationsItem);
    return this;
  }

   /**
   * Get variations
   * @return variations
  **/
  @ApiModelProperty(required = true, value = "")

  public List<WeightedVariation> getVariations() {
    return variations;
  }


  public void setVariations(List<WeightedVariation> variations) {
    this.variations = variations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Distribution distribution = (Distribution) o;
    return Objects.equals(this.bucketBy, distribution.bucketBy) &&
        Objects.equals(this.variations, distribution.variations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bucketBy, variations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Distribution {\n");
    sb.append("    bucketBy: ").append(toIndentedString(bucketBy)).append("\n");
    sb.append("    variations: ").append(toIndentedString(variations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

