/*
 * Harness feature flag service client apis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.harness.cfsdk.cloud.core.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Segment
 */
public class Segment {
  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  private String identifier;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ENVIRONMENT = "environment";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT)
  private String environment;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<Tag> tags = null;

  public static final String SERIALIZED_NAME_INCLUDED = "included";
  @SerializedName(SERIALIZED_NAME_INCLUDED)
  private List<String> included = null;

  public static final String SERIALIZED_NAME_EXCLUDED = "excluded";
  @SerializedName(SERIALIZED_NAME_EXCLUDED)
  private List<String> excluded = null;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<Clause> rules = null;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private Long createdAt;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private Long modifiedAt;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Long version;


  public Segment identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Unique identifier for the segment.
   * @return identifier
  **/
  @ApiModelProperty(required = true, value = "Unique identifier for the segment.")

  public String getIdentifier() {
    return identifier;
  }


  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public Segment name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the segment.
   * @return name
  **/
  @ApiModelProperty(example = "Beta Testers", required = true, value = "Name of the segment.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Segment environment(String environment) {
    
    this.environment = environment;
    return this;
  }

   /**
   * Get environment
   * @return environment
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEnvironment() {
    return environment;
  }


  public void setEnvironment(String environment) {
    this.environment = environment;
  }


  public Segment tags(List<Tag> tags) {
    
    this.tags = tags;
    return this;
  }

  public Segment addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Tag> getTags() {
    return tags;
  }


  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  public Segment included(List<String> included) {
    
    this.included = included;
    return this;
  }

  public Segment addIncludedItem(String includedItem) {
    if (this.included == null) {
      this.included = new ArrayList<>();
    }
    this.included.add(includedItem);
    return this;
  }

   /**
   * Get included
   * @return included
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getIncluded() {
    return included;
  }


  public void setIncluded(List<String> included) {
    this.included = included;
  }


  public Segment excluded(List<String> excluded) {
    
    this.excluded = excluded;
    return this;
  }

  public Segment addExcludedItem(String excludedItem) {
    if (this.excluded == null) {
      this.excluded = new ArrayList<>();
    }
    this.excluded.add(excludedItem);
    return this;
  }

   /**
   * Get excluded
   * @return excluded
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getExcluded() {
    return excluded;
  }


  public void setExcluded(List<String> excluded) {
    this.excluded = excluded;
  }


  public Segment rules(List<Clause> rules) {
    
    this.rules = rules;
    return this;
  }

  public Segment addRulesItem(Clause rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * An array of rules that can cause a user to be included in this segment.
   * @return rules
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "An array of rules that can cause a user to be included in this segment.")

  public List<Clause> getRules() {
    return rules;
  }


  public void setRules(List<Clause> rules) {
    this.rules = rules;
  }


  public Segment createdAt(Long createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }


  public Segment modifiedAt(Long modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * Get modifiedAt
   * @return modifiedAt
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getModifiedAt() {
    return modifiedAt;
  }


  public void setModifiedAt(Long modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public Segment version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getVersion() {
    return version;
  }


  public void setVersion(Long version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Segment segment = (Segment) o;
    return Objects.equals(this.identifier, segment.identifier) &&
        Objects.equals(this.name, segment.name) &&
        Objects.equals(this.environment, segment.environment) &&
        Objects.equals(this.tags, segment.tags) &&
        Objects.equals(this.included, segment.included) &&
        Objects.equals(this.excluded, segment.excluded) &&
        Objects.equals(this.rules, segment.rules) &&
        Objects.equals(this.createdAt, segment.createdAt) &&
        Objects.equals(this.modifiedAt, segment.modifiedAt) &&
        Objects.equals(this.version, segment.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, name, environment, tags, included, excluded, rules, createdAt, modifiedAt, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Segment {\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    included: ").append(toIndentedString(included)).append("\n");
    sb.append("    excluded: ").append(toIndentedString(excluded)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

