/*
 * Harness feature flag service client apis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.harness.cfsdk.cloud.core.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * VariationMap
 */
public class VariationMap {
  public static final String SERIALIZED_NAME_VARIATION = "variation";
  @SerializedName(SERIALIZED_NAME_VARIATION)
  private String variation;

  public static final String SERIALIZED_NAME_TARGETS = "targets";
  @SerializedName(SERIALIZED_NAME_TARGETS)
  private List<String> targets = null;

  public static final String SERIALIZED_NAME_TARGET_SEGMENTS = "targetSegments";
  @SerializedName(SERIALIZED_NAME_TARGET_SEGMENTS)
  private List<String> targetSegments = null;


  public VariationMap variation(String variation) {
    
    this.variation = variation;
    return this;
  }

   /**
   * Get variation
   * @return variation
  **/
  @ApiModelProperty(required = true, value = "")

  public String getVariation() {
    return variation;
  }


  public void setVariation(String variation) {
    this.variation = variation;
  }


  public VariationMap targets(List<String> targets) {
    
    this.targets = targets;
    return this;
  }

  public VariationMap addTargetsItem(String targetsItem) {
    if (this.targets == null) {
      this.targets = new ArrayList<>();
    }
    this.targets.add(targetsItem);
    return this;
  }

   /**
   * Get targets
   * @return targets
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTargets() {
    return targets;
  }


  public void setTargets(List<String> targets) {
    this.targets = targets;
  }


  public VariationMap targetSegments(List<String> targetSegments) {
    
    this.targetSegments = targetSegments;
    return this;
  }

  public VariationMap addTargetSegmentsItem(String targetSegmentsItem) {
    if (this.targetSegments == null) {
      this.targetSegments = new ArrayList<>();
    }
    this.targetSegments.add(targetSegmentsItem);
    return this;
  }

   /**
   * Get targetSegments
   * @return targetSegments
  **/
  @androidx.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTargetSegments() {
    return targetSegments;
  }


  public void setTargetSegments(List<String> targetSegments) {
    this.targetSegments = targetSegments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariationMap variationMap = (VariationMap) o;
    return Objects.equals(this.variation, variationMap.variation) &&
        Objects.equals(this.targets, variationMap.targets) &&
        Objects.equals(this.targetSegments, variationMap.targetSegments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(variation, targets, targetSegments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariationMap {\n");
    sb.append("    variation: ").append(toIndentedString(variation)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("    targetSegments: ").append(toIndentedString(targetSegments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

