/*
 * Harness feature flag analytics service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.harness.cfsdk.cloud.openapi.metric.api;

import io.harness.cfsdk.cloud.openapi.metric.ApiCallback;
import io.harness.cfsdk.cloud.openapi.metric.ApiClient;
import io.harness.cfsdk.cloud.openapi.metric.ApiException;
import io.harness.cfsdk.cloud.openapi.metric.ApiResponse;
import io.harness.cfsdk.cloud.openapi.metric.Configuration;
import io.harness.cfsdk.cloud.openapi.metric.Pair;
import io.harness.cfsdk.cloud.openapi.metric.ProgressRequestBody;
import io.harness.cfsdk.cloud.openapi.metric.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.harness.cfsdk.cloud.openapi.metric.model.Error;
import io.harness.cfsdk.cloud.openapi.metric.model.Metrics;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MetricsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MetricsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MetricsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for postMetrics
     * @param environmentUUID environment parameter in query. (required)
     * @param cluster Unique identifier for the cluster for the account (optional)
     * @param metrics  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postMetricsCall(String environmentUUID, String cluster, Metrics metrics, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = metrics;

        // create path and map variables
        String localVarPath = "/metrics/{environmentUUID}"
            .replace("{" + "environmentUUID" + "}", localVarApiClient.escapeString(environmentUUID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cluster != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cluster", cluster));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postMetricsValidateBeforeCall(String environmentUUID, String cluster, Metrics metrics, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'environmentUUID' is set
        if (environmentUUID == null) {
            throw new ApiException("Missing the required parameter 'environmentUUID' when calling postMetrics(Async)");
        }

        return postMetricsCall(environmentUUID, cluster, metrics, _callback);

    }

    /**
     * Send metrics to the Analytics server.
     * Send metrics to Analytics server
     * @param environmentUUID environment parameter in query. (required)
     * @param cluster Unique identifier for the cluster for the account (optional)
     * @param metrics  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public void postMetrics(String environmentUUID, String cluster, Metrics metrics) throws ApiException {
        postMetricsWithHttpInfo(environmentUUID, cluster, metrics);
    }

    /**
     * Send metrics to the Analytics server.
     * Send metrics to Analytics server
     * @param environmentUUID environment parameter in query. (required)
     * @param cluster Unique identifier for the cluster for the account (optional)
     * @param metrics  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> postMetricsWithHttpInfo(String environmentUUID, String cluster, Metrics metrics) throws ApiException {
        okhttp3.Call localVarCall = postMetricsValidateBeforeCall(environmentUUID, cluster, metrics, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Send metrics to the Analytics server. (asynchronously)
     * Send metrics to Analytics server
     * @param environmentUUID environment parameter in query. (required)
     * @param cluster Unique identifier for the cluster for the account (optional)
     * @param metrics  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postMetricsAsync(String environmentUUID, String cluster, Metrics metrics, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = postMetricsValidateBeforeCall(environmentUUID, cluster, metrics, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
